{"time":"2025-08-01T18:13:14.9965784+02:00","level":"INFO","msg":"stream: starting","core version":"0.19.8","symlink path":"c:\\UNIFI\\LM Bio UniFi\\II ANNO\\SECONDO SEMESTRE\\APPLI OF MACHINE LEARNING\\AML_Labs\\Exercise\\wandb\\run-20250801_181314-c6ecl9pf\\logs\\debug-core.log"}
{"time":"2025-08-01T18:13:16.214423+02:00","level":"INFO","msg":"created new stream","id":"c6ecl9pf"}
{"time":"2025-08-01T18:13:16.2149874+02:00","level":"INFO","msg":"stream: started","id":"c6ecl9pf"}
{"time":"2025-08-01T18:13:16.2155556+02:00","level":"INFO","msg":"writer: Do: started","stream_id":"c6ecl9pf"}
{"time":"2025-08-01T18:13:16.2160858+02:00","level":"INFO","msg":"sender: started","stream_id":"c6ecl9pf"}
{"time":"2025-08-01T18:13:16.2149874+02:00","level":"INFO","msg":"handler: started","stream_id":"c6ecl9pf"}
{"time":"2025-08-01T18:13:16.6464484+02:00","level":"INFO","msg":"Starting system monitor"}
{"time":"2025-08-01T18:13:17.0248401+02:00","level":"INFO","msg":"Pausing system monitor"}
{"time":"2025-08-01T18:13:17.051205+02:00","level":"INFO","msg":"Resuming system monitor"}
{"time":"2025-08-01T18:13:17.0524876+02:00","level":"INFO","msg":"Pausing system monitor"}
{"time":"2025-08-01T18:13:17.0798558+02:00","level":"INFO","msg":"Resuming system monitor"}
{"time":"2025-08-01T18:17:42.7353458+02:00","level":"INFO","msg":"Pausing system monitor"}
{"time":"2025-08-01T18:17:42.746064+02:00","level":"INFO","msg":"Resuming system monitor"}
{"time":"2025-08-01T18:17:44.886919+02:00","level":"INFO","msg":"Pausing system monitor"}
{"time":"2025-08-01T19:06:21.8917223+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/emile-agbedanu-none/AML_Lab1/c6ecl9pf/file_stream\": dial tcp: lookup api.wandb.ai: no such host"}
{"time":"2025-08-01T19:06:45.4095841+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/emile-agbedanu-none/AML_Lab1/c6ecl9pf/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-08-01T19:06:49.6137595+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": read tcp 10.34.0.161:61445->35.186.228.49:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-08-01T19:07:11.0981981+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/emile-agbedanu-none/AML_Lab1/c6ecl9pf/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-08-01T19:07:12.8166147+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-08-01T19:07:38.6434769+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-08-01T19:07:41.7185197+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/emile-agbedanu-none/AML_Lab1/c6ecl9pf/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-08-01T19:08:09.0191125+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-08-01T19:08:21.9201235+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/emile-agbedanu-none/AML_Lab1/c6ecl9pf/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-08-01T19:08:48.0471302+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-08-01T19:09:17.1257926+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/emile-agbedanu-none/AML_Lab1/c6ecl9pf/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-08-01T19:09:45.5481603+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-08-01T19:10:38.172487+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/emile-agbedanu-none/AML_Lab1/c6ecl9pf/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-08-01T19:11:06.5784607+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-08-01T19:11:59.2184302+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/emile-agbedanu-none/AML_Lab1/c6ecl9pf/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-08-01T19:12:27.5934209+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-08-01T19:13:20.2466034+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/emile-agbedanu-none/AML_Lab1/c6ecl9pf/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-08-01T19:13:48.6154318+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-08-01T19:14:41.3056238+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/emile-agbedanu-none/AML_Lab1/c6ecl9pf/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-08-01T19:15:09.6416537+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-08-01T19:16:02.3494939+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/emile-agbedanu-none/AML_Lab1/c6ecl9pf/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
